name: cd.yml
on:
  push:
    branches:
      - main
jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Set up goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: List
        run: ls -lR

      - name: Build prod
        run: scripts/buildprod.sh

      - name: google auth
        uses: 'google-github-actions/auth@v3'
        with:
            credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v3'
        with:
          version: '>= 363.0.0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: "Migrate"
        run: scripts/migrateup.sh

      - name: 'Submit build'
        run: gcloud builds submit --tag australia-southeast2-docker.pkg.dev/notely-473001/notely-ar-repo/notely:latest
    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}