name: cd.yml
on:
  push:
    branches:
      - main
jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Build prod
        run: scripts/buildprod.sh